### PR TITLE
Working branch

### PR DESCRIPTION
**Pull request by ritesh-2124**
landing page completed

### CODE REVIEW

**Comment by ritesh-2124** [comment]
done landing page

**Comment by ritesh-2124** [comment]
done

**Comment by ritesh-2124** [comment]
compleate

**Review by Aniket-Pilankar — APPROVED** [review]
Submitted

**Comment by Aniket-Pilankar** [comment]
c

**Review by Aniket-Pilankar — APPROVED** [review]

**Comment by Aniket-Pilankar** [comment]
done

**Pull request merged**
